### ISSUE TITLE
Getting runtime exception on MediaRecorder.start

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [riul88/call-recorder-for-android#48]
I'm getting the following error could you please help me fixing it?

`Call recorder:: RecordService startRecording
MediaRecorder: start failed: -2147483648
Call recorder:: Exception
System.err: java.lang.RuntimeException: start failed.
System.err:     at android.media.MediaRecorder.start(Native Method)
System.err:     at com.callrecorder.android.RecordService.startRecording(RecordService.java:226)
System.err:     at com.callrecorder.android.RecordService.onStartCommand(RecordService.java:90)
System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3010)
System.err:     at android.app.ActivityThread.-wrap17(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Call recorder:: RecordService terminateAndEraseFile`

Thanks,
Unnikrishnan B.

**Comment by UnnikrishnanBhargavakurup** [comment]
It's working form me when i changed `MediaRecorder.AudioSource.VOICE_CALL` to `MediaRecorder.AudioSource.MIC`

I'm using LG Nexus 5 is there any workaround to handle different phones.

**Comment by ozencelik** [comment]
Thanks @UnnikrishnanBhargavakurup
Your solution worked for me.
